name: liqo_app
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  http: ^0.13.4
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0



flutter:
  
  uses-material-design: true
  assets:
    - images/

  module:
    androidX: true
    androidPackage: com.example.liqo_app
    iosBundleIdentifier: com.example.liqoApp
